[nodes.wrs]
type = "wrs"
suffix = ""
actions = true
enabled = true

[nodes.tts]
type = "tts"
suffix = "-tts"
actions = true
enabled = true

[skills]
observe = "wrs"
move_named_pose = "wrs"
pick = "wrs"
place = "wrs"
verify = "wrs"
speak = "tts"
